// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdbwaHumEh84fQ0-TH_72AyeUTNkF49uk',
    appId: '1:887760860874:web:a5bf9102c5583f05156633',
    messagingSenderId: '887760860874',
    projectId: 'employeeattendance-6360d',
    authDomain: 'employeeattendance-6360d.firebaseapp.com',
    storageBucket: 'employeeattendance-6360d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPEUbn9h89VY3QqTGVhSddGiuYHqXojck',
    appId: '1:887760860874:android:49abf0a65dda9a3d156633',
    messagingSenderId: '887760860874',
    projectId: 'employeeattendance-6360d',
    storageBucket: 'employeeattendance-6360d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWBLCcPH-41raX0PMhXdiuqbomBd-viWw',
    appId: '1:887760860874:ios:3565ce96178a2c2e156633',
    messagingSenderId: '887760860874',
    projectId: 'employeeattendance-6360d',
    storageBucket: 'employeeattendance-6360d.appspot.com',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWBLCcPH-41raX0PMhXdiuqbomBd-viWw',
    appId: '1:887760860874:ios:3565ce96178a2c2e156633',
    messagingSenderId: '887760860874',
    projectId: 'employeeattendance-6360d',
    storageBucket: 'employeeattendance-6360d.appspot.com',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdbwaHumEh84fQ0-TH_72AyeUTNkF49uk',
    appId: '1:887760860874:web:ef1bca608b1c5928156633',
    messagingSenderId: '887760860874',
    projectId: 'employeeattendance-6360d',
    authDomain: 'employeeattendance-6360d.firebaseapp.com',
    storageBucket: 'employeeattendance-6360d.appspot.com',
  );
}
